puts "===== Run Success ======"
puts "Hello World"
puts "Powered by mruby 3.0.0"
puts "===== System Info ======"
puts "Kernel: #{OS.sysname}-#{OS.machine}"
puts "Bit: #{OS.bits}"
puts "Posix: #{OS.posix?}"
