name: Alpine Musl - amd64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PKG_DATE: 20240627
  PLATFORM: linux
  ARCHITECTURES: amd64

jobs:
  make-linux-amd64:
    strategy:
      matrix:
        os: [alpine]
        ruby-version: [3.3.3]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build amd64
        run: |
          ls -al
          gem install rake
          rake build
      - name: "Upload Artifact- osx amd64"
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.PKG_DATE }}-${{env.PLATFORM}}-${{env.ARCHITECTURES}}.tar.gz
          path: build/app.tar.gz
