name: MacOS amd64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PKG_DATE: 20240627
  PLATFORM: osx
  ARCHITECTURES: amd64
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  make-osx-amd64:
    strategy:
      matrix:
        os: [macos-12]
        ruby-version: [3.3.3]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build amd64
        run: |
          ls -al
          gem install rake
          rake release
      - name: "Upload Artifact- osx amd64"
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.PKG_DATE }}-${{env.PLATFORM}}-${{env.ARCHITECTURES}}
          path: app.tar.gz
